import java.util.*;

// Interfaces

interface Payable {
    void payment();
}

interface Manageable {
    void addEmployee(Employee employee);
}

interface Reportable {
    void report();
}

// Common Entity

class Person {
    String name;
    String phoneNo;

    Person(String name, String phoneNo) {
        this.name = name;
        this.phoneNo = phoneNo;
    }
}

// Services

class PaymentService {
    public void generatePayment(String name) {
        System.out.println("Payment generated for " + name);
    }
}

class ReportService {
    public void generateReport(String name) {
        System.out.println("Report generated by " + name);
    }
}

// Employee

class Employee implements Payable, Reportable {

    Person person;
    int salary;

    PaymentService paymentService;
    ReportService reportService;

    Employee(String name, String phoneNo, int salary,
             PaymentService paymentService,
             ReportService reportService) {

        this.person = new Person(name, phoneNo);
        this.salary = salary;
        this.paymentService = paymentService;
        this.reportService = reportService;
    }

    @Override
    public void payment() {
        paymentService.generatePayment(person.name);
    }

    @Override
    public void report() {
        reportService.generateReport(person.name);
    }
}

// Manager

class Manager implements Payable, Reportable, Manageable {

    Person person;
    int salary;

    List<Employee> employees;

    PaymentService paymentService;
    ReportService reportService;

    Manager(String name, String phoneNo, int salary,
            PaymentService paymentService,
            ReportService reportService) {

        this.person = new Person(name, phoneNo);
        this.salary = salary;
        this.paymentService = paymentService;
        this.reportService = reportService;
        this.employees = new ArrayList<>();
    }

    @Override
    public void payment() {
        paymentService.generatePayment(person.name);
    }

    @Override
    public void report() {
        reportService.generateReport(person.name);
    }

    @Override
    public void addEmployee(Employee employee) {
        employees.add(employee);
        System.out.println(
                employee.person.name +
                " added under manager " +
                person.name
        );
    }
}

// Contractor

class Contractor implements Payable {

    Person person;
    int salary;
    String projectName;
    int contractDuration;

    PaymentService paymentService;

    Contractor(String name,
               String phoneNo,
               int salary,
               String projectName,
               int contractDuration,
               PaymentService paymentService) {

        this.person = new Person(name, phoneNo);
        this.salary = salary;
        this.projectName = projectName;
        this.contractDuration = contractDuration;
        this.paymentService = paymentService;
    }

    @Override
    public void payment() {
        paymentService.generatePayment(person.name);
    }

    public void showContractDetails() {
        System.out.println("Project : " + projectName);
        System.out.println("Duration: " + contractDuration + " months");
    }
}

// Driver Class

public class Main {

    public static void main(String[] args) {

        PaymentService paymentService = new PaymentService();
        ReportService reportService = new ReportService();

        Employee e1 = new Employee(
                "Vishnu",
                "9999999999",
                30000,
                paymentService,
                reportService
        );

        Employee e2 = new Employee(
                "Srija",
                "8888888888",
                40000,
                paymentService,
                reportService
        );

        Manager m1 = new Manager(
                "Siri",
                "7777777777",
                70000,
                paymentService,
                reportService
        );

        m1.addEmployee(e1);
        m1.addEmployee(e2);

        e1.payment();
        e1.report();

        m1.payment();
        m1.report();

        Contractor c1 = new Contractor(
                "Manish",
                "6666666666",
                50000,
                "AI Recruitment System",
                6,
                paymentService
        );

        c1.payment();
        c1.showContractDetails();
    }
}